---

version: "3.2"

services:

  blox-workspace:
    image: "hestio/blox:develop"
    hostname: blox-workspace
    network_mode: "host"
    entrypoint: tail -f /dev/null
    volumes:
      # Pass in your AWSH identities and filters
      - ${HOME}/.awsh:/home/awsh/.awsh
      # Pass in your SSH configuration if you connect using SSH with Git
      - ${HOME}/.ssh:/home/awsh/.ssh-local
      # Pass in your AD/Kerberos config if using Kerberos based auth
      - /etc/krb5.conf:/etc/krb5.conf
      - /etc/krb5.conf.d/:/etc/krb5.conf.d/
      # Map this workspace content
      - ../:/workspace
      # Map temporary cache, used by Kerberos and for sharing credentials between host and workspace
      - /tmp:/tmp
    environment:
      # Tip: Activate only the entries you use; http_proxy and https_proxy at a minimum
      HTTP_PROXY: "${http_proxy}"
      http_proxy: "${http_proxy}"
      HTTPS_PROXY: "${https_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
      NO_PROXY: "${no_proxy}"
      # Tip: Do you have a fancy Font with glyphs?
      #   PATCHED_FONT_IN_USE: 'yes'
      # Tip: Are you already authenticated with AD/Kerberos
      KRB5CCNAME: "${KRB5CCNAME}"
